#!/usr/bin/env pwsh
<#
.SYNOPSIS
  Post-provision hook for azd to generate env-config.txt from Bicep outputs.
  This maintains backwards compatibility with existing simulate-issues.ps1 and generate-load.ps1 scripts.

.DESCRIPTION
  After 'azd provision' completes, this script reads Bicep outputs and writes env-config.txt
  in the same format as the old deploy.ps1, allowing simulate-issues and generate-load to
  continue working without modification.

.PARAMETER AzdOutputs
  JSON object containing outputs from 'azd env get-values' (passed by azd automatically).
#>

param(
    [object]$AzdOutputs
)

# Retrieve outputs from azd (these are set as environment variables by azd post-provision)
$frontendUrl = $env:FRONTEND_URL ?? $AzdOutputs.frontendUrl
$backendUrl = $env:BACKEND_URL ?? $AzdOutputs.backendUrl
$appInsightsKey = $env:APP_INSIGHTS_KEY ?? $AzdOutputs.appInsightsInstrumentationKey
$sqlServerFqdn = $env:SQL_SERVER_FQDN ?? $AzdOutputs.sqlServerFqdn
$storageAccountName = $env:STORAGE_ACCOUNT_NAME ?? $AzdOutputs.storageAccountName
$resourceGroupName = $env:AZURE_RESOURCE_GROUP ?? "rg-copilot-demo"
$environmentName = $env:ENVIRONMENT_NAME ?? "demo"

# Extract resource names from URLs/outputs
$frontendAppName = if ($frontendUrl -match 'https://([^.]+)\.azurewebsites\.net') { $matches[1] } else { "" }
$backendAppName = if ($backendUrl -match 'https://([^.]+)\.azurewebsites\.net') { $matches[1] } else { "" }
$sqlServerName = if ($sqlServerFqdn -match '^([^.]+)\.') { $matches[1] } else { "" }

# Build env-config.txt content in the original format
$envConfig = @"
# Auto-generated by azd post-provision on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# Bicep outputs converted to env-config.txt format

RESOURCE_GROUP=$resourceGroupName
ENVIRONMENT_NAME=$environmentName
APP_SERVICE_PLAN=asp-copilot-demo-$environmentName
FRONTEND_APP=$frontendAppName
FRONTEND_URL=$frontendUrl
BACKEND_APP=$backendAppName
BACKEND_URL=$backendUrl
SQL_SERVER=$sqlServerName
SQL_SERVER_FQDN=$sqlServerFqdn
SQL_DATABASE=appdb
APP_INSIGHTS=ai-copilot-demo-$environmentName
APP_INSIGHTS_KEY=$appInsightsKey
STORAGE_ACCOUNT=$storageAccountName
"@

# Write env-config.txt to repo root
$envConfigPath = Join-Path -Path (Get-Item -Path $PSScriptRoot).Parent.FullName -ChildPath "env-config.txt"

try {
    Set-Content -Path $envConfigPath -Value $envConfig -Encoding UTF8
    Write-Host "✓ Generated $envConfigPath" -ForegroundColor Green
    Write-Host "  Existing simulate-issues.ps1 and generate-load.ps1 scripts can now run." -ForegroundColor Cyan
}
catch {
    Write-Host "✗ Failed to write env-config.txt: $_" -ForegroundColor Red
    exit 1
}

# Display summary
Write-Host "`nAzure Resources Provisioned:" -ForegroundColor Cyan
Write-Host "  Frontend: $frontendUrl"
Write-Host "  Backend:  $backendUrl"
Write-Host "  SQL:      $sqlServerFqdn"
Write-Host "  Storage:  $storageAccountName"
Write-Host "  App Insights Key: $appInsightsKey"
